unbind C-b
set-option -g prefix C-g
set-option -g repeat-time 0


bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R


bind-key -n C-h previous-window
bind-key -n C-l next-window

bind | split-window -h
bind - split-window -v
